# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: zjack-api

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless
  stage: dev
  region: us-east-1

# The `functions` block defines what code to deploy
functions:
  test:
    handler: handler.test
    # The `events` block defines how to trigger the handler.test code
    events:
      - http:
          path: test
          method: get
          cors: true
  randomDeck:
    handler: handler.randomDeck
    # The `events` block defines how to trigger the handler.randomDeck code
    events:
      - http:
          path: randomdeck
          method: get
          cors: true
  createRuleTable:
    handler: handler.createRuleTable
    # The `events` block defines how to trigger the handler.createRuleTable code
    events:
      - http:
          path: createruletable
          method: post
          cors: true
